version: '3'

output: prefixed

vars:
  # GOSIM: go run github.com/kmrgirish/gosim/cmd/gosim
  GOSIM: $(pwd)/.gosim/gosimtool
  SIMPACKAGES: ./internal/tests/behavior ./nemesis

tasks:
  fix-fmt:
    cmds:
      - .ci/gofmt fix

  check-fmt:
    cmds:
      - .ci/gofmt check

  go-generate:
    cmds:
      - go generate ./...

  gosim-tool:
    run: once
    cmds:
      - mkdir -p ./.gosim && go build -o ./.gosim/gosimtool ./cmd/gosim

  gosim-prepare-selftest:
    run: once
    cmds:
      - "{{.GOSIM}} prepare-selftest"
    deps:
      - gosim-tool

  go-test:
    cmds:
      - "{{.GOSIM}} build-tests {{.SIMPACKAGES}}"
      - go test -ldflags=-checklinkname=0 -tags=linkname ./...
    deps:
      - gosim-tool
      - gosim-prepare-selftest

  go-race-test:
    cmds:
      - "{{.GOSIM}} build-tests -race {{.SIMPACKAGES}} ./internal/tests/race/testdata"
      # todo: get rid of this janky thing???
      - go test -ldflags=-checklinkname=0 -tags=linkname -race ./...
    deps:
      - gosim-tool
      - gosim-prepare-selftest

  test:
    deps:
      - check-fmt
      - go-test
      - go-race-test

