// Code generated by "stringer -type=traceKey"; DO NOT EDIT.

package gosimruntime

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[traceKeyRunPick-0]
	_ = x[tracekeyRunResult-1]
	_ = x[tracekeyLogWrite-2]
	_ = x[traceKeyCreating-3]
	_ = x[traceKeyRunStarted-4]
	_ = x[traceKeyRunFinished-5]
	_ = x[traceKeyTimeNow-6]
}

const _traceKey_name = "traceKeyRunPicktracekeyRunResulttracekeyLogWritetraceKeyCreatingtraceKeyRunStartedtraceKeyRunFinishedtraceKeyTimeNow"

var _traceKey_index = [...]uint8{0, 15, 32, 48, 64, 82, 101, 116}

func (i traceKey) String() string {
	if i >= traceKey(len(_traceKey_index)-1) {
		return "traceKey(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _traceKey_name[_traceKey_index[i]:_traceKey_index[i+1]]
}
